# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Prompt.create(content: "If we were to have a threesome, which celebrity would you invite?" ,score: 30 )
Prompt.create(content: "What is the perfect penis length and why?" ,score: 30)
Prompt.create(content: "What song gets you \"in the mood\"?" ,score: 15)
Prompt.create(content: "What's that thing you do when no one's looking?" ,score: 15)
Prompt.create(content: "What happened today that you're most thankful for?" ,score: 25)
Prompt.create(content: "You think you're right: bite your tongue or speak your mind?" ,score: 20)
Prompt.create(content: "Last bite: mine or yours?" ,score: 15)
Prompt.create(content: "What's your idea of a romantic meal?" ,score: 20)
Prompt.create(content: "Describe your ideal lighting" ,score: 10)
Prompt.create(content: "Top or bottom??" ,score: 30)
Prompt.create(content: "How do you defy your Zodiac symbol?" ,score: 10)
Prompt.create(content: "Are you thirsty?" ,score: 20)
Prompt.create(content: "What's your definition of third base?" ,score: 20)
Prompt.create(content: "Time for a tough conversation: text, phone call, or in person?" ,score: 15)
Prompt.create(content: "To eat the ass, or not to eat the ass, that is the question" ,score: 40)
Prompt.create(content: "What's the thing that you can't bear to throw away?" ,score: 15)
Prompt.create(content: "You want to take it to the next level with me: what kind of movie do you take me to?" ,score: 10)
Prompt.create(content: "Tell me something I don't know!" ,score: 50)
Prompt.create(content: "I'm going on a diet!" ,score: 20)
Prompt.create(content: "Decribe our relationship with emojis." ,score: 5)
Prompt.create(content: "What are you hiding?" ,score: 30)
Prompt.create(content: "What's the best relationship you've ever been in?" ,score: 30)
Prompt.create(content: "I'm sick, what are you going surprise me with?" ,score: 20)
Prompt.create(content: "I'm not sick, what are you going to surprise me with?" ,score: 20)
Prompt.create(content: "We're going on a trip: plan every little detail or play it by ear?" ,score: 10)
Prompt.create(content: "You were right: \"told you so\" or be silently smug?" ,score: 10)
Prompt.create(content: "我和你妈妈掉水里了你先救谁" ,score: 100)
Prompt.create(content: "when do you want to get married？" ,score: 100)
Prompt.create(content: "打算什么时候结婚?" ,score: 100)
Prompt.create(content: "结婚彩礼多少合适" ,score: 100)
Prompt.create(content: "I am a dirty dirty spy", score: 1000000)
Prompt.create(content: "how many ex do you have before？" ,score: 15)
Prompt.create(content: "When I and your mom accidently" ,score: 10)
Prompt.create(content: "If you could be any animal, what would you be?" ,score: 20)
Prompt.create(content: "Why do some people stay in relationships that they know are toxic?")
Prompt.create(content: "Describe the perfect version of yourself." )
Prompt.create(content: "Do you think the future will be better than the present? Why?")
Prompt.create(content: "What's the most crucial thing for a healthy relationship?")
Prompt.create(content: "What lies do you most often tell yourself?")
Prompt.create(content: "What stops people from achieving their dreams?")
Prompt.create(content: "Why are there so many lonely people when almost everyone wants to make real connections?")
Prompt.create(content: "Why does society value beauty so much when it serves no functional purpose?")
Prompt.create(content: "Describe your perfect life from hereon.")
Prompt.create(content: "Have you ever cheated on someone before? What happened?")
Prompt.create(content: "What was your most serious relationship and why did it end?")
Prompt.create(content: "List 3 annoying things that your partner does", score: 20)
Prompt.create(content: "List 3 of the best things that your partner does")
Prompt.create(content: "What was the most adventurous thing you've ever done?")
Prompt.create(content: "Do you prefer being indoors or outdoors?")
Prompt.create(content: "What 3 objects do you value the most?")
Prompt.create(content: "How many sexual partners have you had?")
Prompt.create(content: "What 2 things would you like more of while having sex?")
Prompt.create(content: "Is there anything you'd like to try in the bedroom that you've been afraid to ask for?")
Prompt.create(content: "How often do you like having sex?", score:15)
Prompt.create(content: "What do you think is worth spending extra money on?")
Prompt.create(content: "What do you think is a waste of money?")
Prompt.create(content: "What do you think is worth spending extra money on?")
Prompt.create(content: "In a relationship, when should each partner pay for something and when should they split the cost?")
Prompt.create(content: "What do you know that you aren't supposed to know?")
Prompt.create(content: "What's the scariest story you've ever heard?")
Prompt.create(content: "What's the most romantic thing you've heard about someone doing for someone else?")
Prompt.create(content: "What are some things that you could never quite understand?")
Prompt.create(content: "What 30 seconds would you erase from your life if you could?")
Prompt.create(content: "Would you get into a relationship with yourself (assuming the other you is the gender you're attracted to)?")
Prompt.create(content: "What mistakes in your life have you learned the biggest lessons from?")
Prompt.create(content: "What's your favorite piece of clothing?")
Prompt.create(content: "What are the most annoying things that happen on social media?")
Prompt.create(content: "What causes you to look down on someone?")
Prompt.create(content: "What do you need to vent about?")
Prompt.create(content: "What's your idea of success?")
Prompt.create(content: "What would you like your last meal to be?")
Prompt.create(content: "What's the worst non-illegal habit someone can have?")
Prompt.create(content: "What's the best way to spend a rainy afternoon?")
Prompt.create(content: "If the internet was going to be cut off forever at the end of the day, what would you try to download?")
Prompt.create(content: "How often do you dance?")
Prompt.create(content: "When are you the most comfortable?")
Prompt.create(content: "How good are you at keeping secrets?")
Prompt.create(content: "What would be the perfect pet?")
Prompt.create(content: "What was the most thoughtful gift you've ever received?")
Prompt.create(content: "What's the most embarassing clothing malfunction you've had?")
Prompt.create(content: "What do you look forward to?")
Prompt.create(content: "How hard do you work to improve yourself?")
Prompt.create(content: "What's something that many people find unattractive in a person, but you really like?")
Prompt.create(content: "What do you wish you could change about yourself?")
Prompt.create(content: "What do you wish you had started a long time ago?")
Prompt.create(content: "If you could be any animal, what would you be?")
Prompt.create(content: "What do you consider your greatest weakness?")
Prompt.create(content: "What is your favorite thing to do?")
Prompt.create(content: "Have you ever been heartbroken?")
Prompt.create(content: "Who is your favorite fictional character?")
Prompt.create(content: "What does love look like to you?")
Prompt.create(content: "What is your favorite dessert?")
Prompt.create(content: "What's your least favorite personality trait? What's your least favorite personality trait? ")
Prompt.create(content: "What's your least favorite personality trait? ")
Prompt.create(content: "If you had to kill someone, who would it be and why? ")
Prompt.create(content: "What do you fear the most? ")
Prompt.create(content: "What gave you the worst bout of food poisoning and where were you?")
Prompt.create(content: "Which civil rights hero are you? ")
Prompt.create(content: "Which Bond villain are you? ")




